import "./minecraft/crystals.js";
import "./minecraft/glowstone.js";
import "./minecraft/fungi.js";
import "./minecraft/leaves.js";
import "./minecraft/logs.js";
import "./minecraft/ores.js";
import "./minecraft/plants.js";
import "./minecraft/sculk-family.js";
import "./minecraft/shrooms.js";
